language: php
php:
  - '7.1'

services:
  - docker

before_install:
  - docker build -t cotodo/cotodo .

install:
  - composer install

addons:
  sonarcloud:
    organization: "cotodo"

script:
  - ./bin/phpunit --verbose
  - sonar-scanner
